### PR TITLE
Rebuild for libboost 1.82

### PR DESCRIPTION
**Pull request by h-vetinari**
Currently WIP, because I don't understand why everything is pinned so incredibly tightly here. In any case, the cgal pins make it impossible for the migration bot to resolve.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@srmnitc 
Can you explain what made it necessary to pin the runtime dependencies so tightly? And can we express that in the form of running a test (or a test suite, if there's one upstream), so that we ensure the package stays functional, without making it pin so tightly (which is really for keeping this package usable over time).

**Comment by srmnitc** [comment]
> @srmnitc Can you explain what made it necessary to pin the runtime dependencies so tightly? And can we express that in the form of running a test (or a test suite, if there's one upstream), so that we ensure the package stays functional, without making it pin so tightly (which is really for keeping this package usable over time).

@h-vetinari The tight pinning came from the recommendation of one of the developers. I am tagging him here, and will also reach out. I will also get him onboard as a maintainer. @mkuehbach could you please take a look?

**Comment by h-vetinari** [comment]
Gentle ping @mkuehbach; pinning as tightly as this recipe does (before this PR) is problematic for the resolver, and hostile to other packages that a users wants to install side-by-side with paraprobe. It would therefore be good to loosen this (as I've done), but I don't want to break the usage of the package, of course.

**Comment by h-vetinari** [comment]
Ping @srmnitc @mkuehbach

**Comment by mkuehbach** [comment]
Dear @h-vetinari
Thank you very much for your comments and feedback on this point. Its @mkuehbach writing, the lead developer behind the paraprobe-toolbox project. This topic about dependencies management has two points with aims that requires (not infrequently)
to make compromises in directions which are not always pointing into the same direction:

When the aim is to install paraprobe-toolbox primarily as a toolbox for adding new functionalities and source code, you are right, people might need to add packages and in the process but may face challenges when these additional packages are in conflict with the here more tightly pinned deps. The typical solution is to release some constraints, which results usually in successful case-by-case solutions to make the local changes for the developer working, I am not so much a fan of such ad hoc decisions.

Namely, when the aim is to use conda for offering end users an easier installation of a complex package like paraprobe-toolbox - and this is for now our primary aim with using conda for paraprobe-toolbox - I argue that the dependencies as they are not even pinned down enough. Why? It is the numerical reproducibility aspect. One fantastic benefit of version and package management tools like conda and others is that you can pinpoint tools to specific dependencies to at least reduce the sources where possibly different code can generate different numerical results. I am not stating that all such potential numerical differences are always significant in practice but who knows this a priori, I don't but I know many often simply guess these differences are insignificant. I am not convinced about this. For this reason, the strategy with paraprobe-toolbox has always been, nonetheleast given the software tools' strong focus on computational geometry, to pin down tightly.

I am aware of the fact that even with having pinned down all dependencies tightly will not necessarily result in that two users on two target systems will get necessarily exactly the same executable and numerical results. However, there is substantiated evidence to argue that their results will be less affected by changes between versions as if one wouldnt pin down tightly, especially when the time between installations differs strong as unconstrained deps are also implicitly constrained in that they point to whatever is latest.

So much about the ideas and contextualization to address your question.

Now in the here discussed case, your changes indeed should not cause substantial issues, so I second your proposed changes. In my opinion, though, the best option to go with in the future is first to implement a mechanism in each tool which tracks the exact execution context i.e. the versions of all packages inside the conda environment, I had experimented with it but at the time this was not working, your comment motivates me to have a look on this again.
Either way, this is work on two fronts - constraint management and documentation - and I agree paraprobe-toolbox would profit from having improved both

**Comment by h-vetinari** [comment]
Hey @mkuehbach, thanks for sharing your thoughts!

> I argue that the dependencies as they are not even pinned down enough. Why?

you are conflating two different things here:
* expressing the required versions constraints necessary to run the code at all (dependent on what features of your dependencies you use, and in which version they got introduced, removed resp. considered bugfree)
* pinning/locking dependencies for testing/deployment/reproducibility

The job of the feedstock is explicitly the former. The latter is the responsibility (and choice!!) of the user. If you try to do the latter through the feedstock, you are at best being patronizing towards your users - consenting adults and all that - saying they're not allowed (through incompatible solver constraints) to install the package with marginally different dependencies (which they might require for _other_ packages), and often makes installability in a non-minimal environment impossible in the first place, which is really user-hostile because there's no work-around, much less any choice.

I understand the desire to smooth the path of your users towards success as much as possible, and there's nothing wrong with that of course! It's just that controlling your dependencies that tightly does not fit into a distributed ecosystem where your package is one citizen among many. In other words, if everyone pinned as hard as paraprobe does at the moment, nothing would be installable anymore.

So my preferred way of solving this would be to help users understand what they need to do to ensure numerical reproducibility (if they care about it!), things like `conda env export -f lock.yml` etc.

If that's not enough in your eyes, we could also add an additional output `paraprobe-tight` or `paraprobe-curated` that depends on the more loosely-pinned `paraprobe` (where all the content resides), but then pins as tightly as you feel like it. That way the default is sane, but people who want your pre-approved setup have a simple way to get it.

**Comment by h-vetinari** [comment]
Gentle ping @mkuehbach

**Comment by h-vetinari** [comment]
Ping @mkuehbach

**Comment by h-vetinari** [comment]
Ping @mkuehbach

**Comment by srmnitc** [comment]
@h-vetinari I am going to update this tool to the next version, so I will go ahead and merge this in. Imo I will test the pinning of requirements, and add a `paraprobe-tight` or so if needed. Sorry about the delay here.

**Pull request merged**
